name: AutoMSG
version: ${project.version}
main: com.comonier.automsg.AutoMSG
api-version: 1.19
commands:
  am:
    description: Professional Announcement System
    permission: automsg.admin
    usage: /am [reload|list|add|remove] [category] [value]
permissions:
  automsg.admin:
    description: Allows full access to AutoMSG management.
    default: op
